--- #YAML:1.0
name:               Mojolicious-Plugin-ISAjax
version:            1.00
abstract:           Browses online documentation of your Mojolicious application
author:
    - Viliam Pucik <viliam.pucik@gmail.com>
license:            artistic_2
distribution_type:  module
configure_requires:  {}
build_requires:  {}
requires:
    Mojolicious:  1.80
    perl:         5.008007
resources:
    homepage:    https://github.com/viliampucik/Mojolicious-Plugin-ISAjax
    license:     http://dev.perl.org/licenses/
    repository:  git://github.com/viliampucik/Mojolicious-Plugin-ISAjax.git
no_index:
    directory:
        - t
        - inc
        - t
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
